name: Lib Tag

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'oracle'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Set release version from tag
        run: |
          VERSION=${GITHUB_REF_NAME}
          mvn -B versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false

      - name: Build & publish
        run: mvn -B deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README with released version
        run: |
          VERSION=${GITHUB_REF_NAME}
          sed -i 's|<version>.*</version>|<version>'"$VERSION"'</version>|' README.md

      - name: Bump to next SNAPSHOT version
        run: |
          CURRENT=${GITHUB_REF_NAME}
          
          # Remove leading v and any suffix like -SNAPSHOT
          CLEAN=${CURRENT#v}
          CLEAN=${CLEAN%%-*}
          
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CLEAN"
          NEXT="$MAJOR.$MINOR.$((PATCH + 1))"
          
          mvn -B versions:set \
            -DnewVersion="${NEXT}-SNAPSHOT" \
            -DgenerateBackupPoms=false

      - name: Commit snapshot + README update
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add pom.xml README.md
          git commit -m "chore: release $CURRENT and bump to $NEXT-SNAPSHOT"
          git push